### ISSUE TITLE
Cluster onTap: access ClusterManager and MapController...

### ISSUE THREAD

**Issue by mistyn8** [coletiv/flutter_google_maps_clusters#6]
Nice job...
So I'm wanting to extend so that tapping a cluster icon can show a list of clutered markers, and position the cluster marker on the center of the screen.
It would appear that the ClusterMarker doesn't know about it's clustermanager or indeed the mapController..
Is the best way to do this to pass those references into the toMarker() method?

Something like this.

```
Marker toMarker(
          Fluster<MapMarker> _fluster, GoogleMapController mapController) =>
      Marker(
          anchor: isCluster ? const Offset(.5, .5) : const Offset(.5, 1),
          markerId: MarkerId(isCluster ? 'cl_$id' : id),
          position: LatLng(
            position.latitude,
            position.longitude,
          ),
          icon: icon,
          infoWindow: InfoWindow(
            title: markerId,
            //onTap: () => doSomething(), //TODO implement this bit
          ),
          onTap: () async {
            print('taped $isCluster');
            if (isCluster) {
              List<MapMarker> cluster = _fluster.children(clusterId);
              await mapController
                  .animateCamera(CameraUpdate.newLatLngZoom(position, await mapController.getZoomLevel() + 1));
              //await mapController.animateCamera(CameraUpdate.zoomIn());
              for (var marker in cluster) {
                print(marker.position.toString());
              }
            }
          });
```

with corresponding updates to 

```
 static Future<List<Marker>> getClusterMarkers(
    GoogleMapController mapController,
    Fluster<MapMarker> clusterManager, ...
```

```
final updatedMarkers = await MapHelper.getClusterMarkers(
      mapController,
      _clusterManager, ...
```

**Comment by biklas7** [comment]
Hi @mistyn8 sorry for the late response.

I don't think that's a good idea.

To center the map on the cluster marker I suggest the following:

Update the `MapMarker` class to have a new `final Function onTap;` property and update the `toMarker()` to register the `onTap` callback once the `Marker` is created.

Then, you can try to pass a function callback like `onClusterTap(LatLng clusterLocation)` to the `initClusterManager` method and when you create a `Fluster` instance, on the `createCluster` you can call `onClusterTap` like so `onTap: () => onClusterTap(LatLng(latitude: lat, longitude: lng))`.

To get the children markers of a cluster you can use `clusterManager.children(clusterId)` this will get you a list of `MapMarker` but be careful because a cluster can have another cluster as children. You can verify if a `MapMarker` is a cluster by using the `isCluster` bool.

This should be enough for you to get a list of the markers that are inside a cluster.

I hope that this is understandable and that it helps you implement your use case. If you have more questions feel free to comment here.

Thanks :+1:

**Comment by mistyn8** [comment]
I don't think that was late at all, thanks kindly for the response.
I tried what you suggested, but seem to not be able to get all the parts working together.. either the clustermanager doens't know about markerprops.. or the marker doesn't know about the clustermanager. :-(
I don't suppose you have time to illustrate with a code sample?

cheers...

**Comment by biklas7** [comment]
I don't have much time now but I will try to get back to you with some code.

Cheers

**Comment by mistyn8** [comment]
No worries.. I realise I was being cheeky... :-)
